name: des-agent
channels:
  - conda-forge
dependencies:
  - fastmcp
  - pandas
  - python=3.11
  - jupyterlab
  - pip
  - numpy
  - matplotlib
  - seaborn
  - simpy
  - tabulate
  - langgraph
  - pip:
      - langchain
      - langchain-community
      - langchain-core
      - langchain-ollama
