name: des-agent
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - pip
  - pip:
      - langchain
      - langchain-community
      - langchain-core
      - langchain-ollama
      - requests
